### ISSUE TITLE
Fix main logo

### ISSUE THREAD

**Issue by cosden** [USRSE/blog#27]
Just showed someone the website and blog and discovered the logo was broken.  
Screenshot:
![image](https://user-images.githubusercontent.com/5824618/65074527-09bece00-d963-11e9-94e3-10c8d30bd7e7.png)

**Comment by vsoch** [comment]
Not surprised, because it was linked from the logos repo - the intention was to keep a consistent file name for a shared logo but that hasn’t been followed, and I’m not managing that repo anymore. I’d normally jump on this but I’m afk for a few more days, so someone else needs to take charge.

**Comment by vsoch** [comment]
Okay did a quick fix! Phew.

**Comment by cosden** [comment]
Thanks @vsoch!  I had to run as soon as I posted this.  I was pretty sure it was going to be an easy fix and I could have done it today, I just didn't want it to slip through the cracks.

**Comment by vsoch** [comment]
I harnessed all my ninja skills to get my laptop to where there was free wireless and made it work!
