### ISSUE TITLE
Community Blog page needs theme update

### ISSUE THREAD

**Issue by suednimh** [USRSE/blog#36]
Community Blog page needs logo and color scheme to match main pages
<img width="1237" alt="logo_theme-blog" src="https://user-images.githubusercontent.com/32795160/136865404-6b63cf1c-5f2e-4d0d-a7c0-5b7c2f06eb8b.png">

**Comment by vsoch** [comment]
Probably the same changes I made to the map https://us-rse.org/usrse-map/ can be done for the blog as well.

**Comment by vsoch** [comment]
@suednimh if you care to review! https://github.com/USRSE/blog/pull/37
