### ISSUE TITLE
CircleCI Workflow update to GitHub Actions

### ISSUE THREAD

**Issue by vsoch** [USRSE/blog#38]
Hi USRSE! The repository here is deploying via my bot's token, and I can no longer provide this and want to suggest you update to perform the push in GitHub actions. Don't worry - I already wrote the workflow: https://github.com/hpc-social/blog/blob/main/.github/workflows/update-posts.yaml just need someone to add it here. I'll revoke my bot permissions at the end of the week, but let me know if you need more time. Thanks!

**Comment by christophernhill** [comment]
@vsoch sounds good. Thanks for the heads up, and for the awesome `update-posts.yaml` all ready to go. 
I can try this out later today, so end of week should be fine. Thanks, hope all  is well - Chris.

**Comment by vsoch** [comment]
Thank you @christophernhill !

**Comment by vsoch** [comment]
Closed with #39 thank you!
