### ISSUE TITLE
"Mins read" number wrong

### ISSUE THREAD

**Issue by cosden** [USRSE/blog#6]
The number listed for some blogs in "XYZ mins read" where XYZ is number is showing up as strange values for some blogs:

For example the US-RSE goals post says "57 1 min read"

![image](https://user-images.githubusercontent.com/5824618/57744374-fd65f400-7696-11e9-8e97-6e2e882607fd.png)

**Comment by vsoch** [comment]
That looks like a bug - I’ll take a look tomorrow!

**Comment by vsoch** [comment]
Just kidding, easy fix! Here we go : https://github.com/USRSE/blog/pull/7
