### ISSUE TITLE
Change "About" to reflect blog

### ISSUE THREAD

**Issue by cosden** [USRSE/blog#9]
Can we change the "About" page to refer to what the blog is all about?  Rather than US-RSE?  Something along the lines (but expanded) of what's at the top of the README?  I can take a stab at later this week.

**Comment by vsoch** [comment]
Sure thing! I put it there mostly for filler. I'll assign you to this issue, and please ping me if/when you are working if you want to discuss, Google Doc it out, or whatever your preference for writing things! Or I'm happy to give feedback on something that you've written up.

**Comment by cosden** [comment]
Done in #18.
